/*
 Copyright 2017 IBM Corp.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

const log4js = require("log4js");
const logger = log4js.getLogger("appid-serversdk-node");
logger.info("Initializing");

var accessTokenString = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpPU0UifQ.eyJpc3MiOiJpbWYtYXV0aHNlcnZlci5zdGFnZTEtZGV2Lm5nLmJsdWVtaXgubmV0IiwiZXhwIjoxNDg1NTUwNDMxLCJhdWQiOiI3NDFlZmM4NjhiOWEzZjM3YjFjZWE1YjFhNTBkNTBmNzQxODJkZmI0IiwiaWF0IjoxNDg1NTQ2ODMxLCJhdXRoX2J5IjoiZmFjZWJvb2siLCJ0ZW5hbnQiOiI2NmY3OWFiOS1hNTRlLTRmYTItYWQzYy00MDZkZjQ5NGQwMTgiLCJzY29wZSI6ImRlZmF1bHQifQ.JmRXVyY77zXLbkHGmyfdD6yI_ZmfF7J0WYqsvuQYheZikna-IHdffvLd-0NXlb9BRHThrKdLqVoNRRqlrBGhkdLNvSZbp3vR2Uddp5xbK0g5n3pjfkn5r-DKyStI-sxyi6xlV5YhdKhkiacrQ_14qa8aP1hJItW4XhoTyZBJZjk7I5dfYkeErXbjHA4k51J0cqHrzPtZl200phq91R4Uh2g3WkJrz9jOkvFzJJ1vzVDHy8VeOwce3ttxsmUDnuHcqBdlGEIe5H6Fw5zbPb5WWnTDDpIivFe6MhHswho0Qy59LAVKKSvIKLcyVe9MkWyqnQDpqig3xbcFuUSwzqnc9w";

var identityTokenString = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpPU0UifQ.eyJpc3MiOiJpbWYtYXV0aHNlcnZlci5zdGFnZTEtZGV2Lm5nLmJsdWVtaXgubmV0IiwiYXVkIjoiNzQxZWZjODY4YjlhM2YzN2IxY2VhNWIxYTUwZDUwZjc0MTgyZGZiNCIsImV4cCI6MTQ4NTU1MDQzMSwiYXV0aF9ieSI6ImZhY2Vib29rIiwidGVuYW50IjoiNjZmNzlhYjktYTU0ZS00ZmEyLWFkM2MtNDA2ZGY0OTRkMDE4IiwiaWF0IjoxNDg1NTQ2ODMxLCJuYW1lIjoiRG9uIExvbiIsImdlbmRlciI6Im1hbGUiLCJsb2NhbGUiOiJrb19LUiIsInBpY3R1cmUiOiJodHRwczovL3Njb250ZW50Lnh4LmZiY2RuLm5ldC92L3QxLjAtMS9wNTB4NTAvMTM1MDE1NTFfMjg2NDA3ODM4Mzc4ODkyXzE3ODU3NjYyMTE3NjY3MzA2OTdfbi5qcGc_b2g9MjQyYmMyZmI1MDU2MDliNDQyODc0ZmRlM2U5ODY1YTkmb2U9NTkwN0IxQkMiLCJpZGVudGl0aWVzIjpbeyJwcm92aWRlciI6ImZhY2Vib29rIiwiaWQiOiIzNzc0NDAxNTkyNzU2NTkifV0sIm9hdXRoX2NsaWVudCI6eyJ0eXBlIjoibW9iaWxlYXBwIiwic29mdHdhcmVfaWQiOiJjb20uaWJtLm1vYmlsZWZpcnN0cGxhdGZvcm0uYXBwaWQiLCJzb2Z0d2FyZV92ZXJzaW9uIjoiMS4wIiwiZGV2aWNlX2lkIjoiZWVlMmM3OGQtMGYxMi0zODA4LTkxZWItYzYzNDc1ZGJiZjk1IiwiZGV2aWNlX21vZGVsIjoiR1QtSTk1MDAiLCJkZXZpY2Vfb3MiOiJhbmRyb2lkIn19.h_ksq84XW3Jf-sChbPUl_BBX318ZyBbPEj-fsJ8t0ABFtyMSJcst35FguCyzwPO-Qodd8leRCgfzdALkmJWMrWtIw_HKhP61v2dw1_0OmaVeB5TUPGFGLRDvPB2mRNBaX8KJoYBiGofd3vjb85o-TwjN0gGnTwkQrO-xSTXAZLw4ou5_QMdycXawCUrxpUCxOuIfAOsXP7F4pJaZBqBo9BVEMeSyMKztpLoGYEZaD6vnVpPEHmajkcpCDzCNyb-YXkvGSRmd03yep-2jV6vvrUX2ss7eaZGJfzS_XkCnxXZ6H9knAPwcyq0QnYoHrkPJfVMhi1G5VJwRiKMT2P2twg";

const tokenUtils = require("./utils/tokenUtils");

tokenUtils.decodeAndValidate(accessTokenString).then(function (token) {
	logger.info(token);
})

tokenUtils.decodeAndValidate(identityTokenString).then(function (token) {
	logger.info(token);
})

