module.exports = {
	VCAP_SERVICES: "VCAP_SERVICES",
	VCAP_SERVICES_CREDENTIALS: "credentials",
	VCAP_SERVICES_SERVICE_NAME1: "AdvancedMobileAccess",
	VCAP_SERVICES_SERVICE_NAME2: "AppID",
	VCAP_APPLICATION: "VCAP_APPLICATION",
	TENANT_ID: "tenantId",
	CLIENT_ID: "clientId",
	SECRET: "secret",
	OAUTH_SERVER_URL: "oauthServerUrl",
	REDIRECT_URI: "redirectUri",
	PREFERRED_LOCALE: "preferredLocale",
	ISS: "iss",
	AUD: "aud",
	EXP: "exp",
	TENANT: "tenant",
	VERSION: "ver",
	CUSTOM_IDENTITY_GRANT_TYPE: "urn:ietf:params:oauth:grant-type:jwt-bearer",
	USER_PROFILE_SERVER_URL : "profilesUrl",
	APP_TO_APP_GRANT_TYPE: "client_credentials",
	TOKEN_PATH: "/token",
	APPID_SERVICE_ENDPOINT: "appidServiceEndpoint",
	APPID_SERVICE_VERSION: "version",
	APPID_TENANT_ID: "tenantId",
	APPID_ISSUER: "issuer"
};
