# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Quality CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ development, master ]

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm install
    - run: npm install -g codecov
    - run: npm run coverage
    - run: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js # publish coverage info to coveralls
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GH_TOKEN }}